src/img_web/urls.py
from django.urls import include, path, re_path
import img_web.settings as settings
import img_web.app.views as views
from django.contrib import admin
from django.contrib.auth.views import LoginView
admin.autodiscover()

app_urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'submit/$', views.submit, name='img-app-submit'),
    re_path(r'queue/$', views.queue, name='img-app-queue'),
    re_path(
        r'queue/filter/$', views.queue,
        kwargs={'dofilter': True},
        name='img-app-queue-filter',
    ),
    re_path(
        r'queue/filter/(?P<queue_name>\S+?)/$', views.queue,
        kwargs={'dofilter': True},
        name='img-app-queue-filter-name',
    ),
    re_path(
        r'queue/(?P<queue_name>\S+?)/$', views.queue,
        name='img-app-queue-name',
    ),
    re_path(
        r'job/delete/(?P<msgid>\S+)$', views.delete_job,
        name='img-app-delete-job',
    ),
    re_path(
        r'job/retry/(?P<msgid>\S+)$', views.retry_job,
        name='img-app-retry-job',
    ),
    re_path(
        r'job/retest/(?P<msgid>\S+)$', views.retest_job,
        name='img-app-retest-job',
    ),
    re_path(
        r'job/togglepin/(?P<msgid>\S+)$', views.toggle_pin_job,
        name='img-app-toggle-pin-job',
    ),
    re_path(
        r'job/(?P<msgid>\S+)$', views.job,
        name='img-app-job',
    ),
    re_path(
        r'search/(?P<tag>\S+)$', views.search,
        name='img-app-search-tag',
    ),
    re_path(
        r'search/', views.search,
        name='img-app-search',
    ),
    re_path(
        r'$', views.index,
        name='index',
    ),
    path(
        'login/', LoginView.as_view(template_name='users/login.html'),
        name="login",
    ),
]

urlpatterns = [
    re_path(r'^%s/' % settings.url_prefix, include(app_urlpatterns)),
]

src/img_web/app/forms.py
# Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
# Contact: Ramez Hanna <ramez.hanna@nokia.com>
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenforms.pyses/>.

""" Image job creation forms """

import os
import re
import glob
from django import forms
from django.forms.formsets import BaseFormSet, formset_factory
from taggit.forms import TagField
from img_web import settings
from img_web.app.models import ImageType, Arch, BuildService, Token
from img_web.app.features import list_features, expand_feature
from django.utils.encoding import smart_str


class extraReposForm(forms.Form):

    obs = forms.ChoiceField(
        label="OBS",
        choices=[("None", "None")],
        help_text="Extra OBS instances from which packages may be downloaded "
                  "from.",
    )
    project = forms.CharField(
        label="Project",
        required=False,
        max_length=500,
        help_text="Project name in which the repository lives. "
                  "For example: home:user",
    )
    repo = forms.CharField(
        label="Repository",
        required=False,
        max_length=500,
        help_text="Repository name in which the packages live. "
                  "For example: latest_i486",
    )

    def __init__(self, *args, **kwargs):
        super(extraReposForm, self).__init__(*args, **kwargs)
        self.fields['obs'].choices = [("None", "None")] + \
            [(obs.apiurl, obs.name) for obs in BuildService.objects.all()]

    def clean(self):
        cleaned_data = self.cleaned_data
        if 'obs' not in cleaned_data or cleaned_data['obs'] == "None":
            cleaned_data['obs'] = None

        if 'repo' not in cleaned_data or cleaned_data['repo'] == "":
            cleaned_data['repo'] = None
        else:
            cleaned_data['repo'] = cleaned_data['repo'].strip()

        if 'project' not in cleaned_data:
            cleaned_data['project'] = ""
        else:
            cleaned_data['project'] = cleaned_data['project'].strip()

        if cleaned_data['obs'] and not cleaned_data['repo']:
            raise forms.ValidationError(
                "You chose an extra OBS without adding a corresponding "
                "repository."
            )
        return cleaned_data


extraReposFormset = formset_factory(extraReposForm)


class extraTokensForm(forms.Form):

    def __init__(self, *args, **kwargs):
        super(extraTokensForm, self).__init__(*args, **kwargs)
        for token in Token.objects.all():
            self.fields[token.name] = \
                forms.CharField(
                    label=token.name,
                    initial=token.default,
                    required=False,
                    help_text=token.description,
                )


extraTokensFormset = formset_factory(extraTokensForm)


class PostProcessForm(forms.Form):

    def __init__(self, *args, **kwargs):
        pp = kwargs.pop("pp", None)
        super(PostProcessForm, self).__init__(*args, **kwargs)
        if pp:
            self.fields[pp.name] = forms.BooleanField(
                label=pp.name, initial=pp.default,
                required=False, help_text=pp.description,
            )
            if pp.argname:
                self.fields[pp.argname] = forms.CharField(
                    label=pp.argname, required=False,
                    widget=forms.Textarea(attrs={'rows': '1'}),
                    help_text=pp.description,
                )


class BasePostProcessFormset(BaseFormSet):

    # The BaseFormSet method ignores index. I think it's broken This
    # assumes form_kwargs is a list with a dict of kwargs per
    # form. Which I think makes sense.
    def get_form_kwargs(self, index):
        try:
            return self.form_kwargs[index]
        except LookupError:
            return {}


# In the ImageJobForm, when a template is selected from the dropdown
# the features associated with that template are automatically ticked;
# essentially providing a set of default features per template.  This
# is done by reading and parsing each of the ks files in the Form and
# passing the feature data to the dropdown by setting the value of
# each 'features' ChoiceField choices element to be a tuple instead of
# a simple value. The create_option method 'decodes' this to the plain
# value and attrs so the builtin template renders them correctly as
# data- attrs. Returned data is also validated against just the plain
# value. JavaScript in the upload.html template then sets these values
# using the per-option data- attributes
class OptionAttrChoiceField(forms.ChoiceField):

    def valid_value(self, value):
        "Check to see if the provided value is a valid choice"
        for choice in self.choices:
            k = choice[0]
            if isinstance(k, (list, tuple)):  # This needs decoding
                k = k[0]  # so pick the 'value' and discard attrs
            v = choice[1]
            if isinstance(v, (list, tuple)):
                # This is an optgroup, so look inside the group for options
                for k2, v2 in v:
                    if value == smart_str(k2):
                        return True
            else:
                if value == smart_str(k):
                    return True
        return False


class OptionAttrSelect(forms.Select):
    # This is the mainly standard method called per-option to be
    # passed to the template value can now be a value or a tuple/list
    # of (value, dict_of_attrs)
    def create_option(self, name, value, label, selected, index,
                      subindex=None, attrs=None):
        index = str(index) if subindex is None else "%s_%s" % (index, subindex)
        if attrs is None:
            attrs = {}
        option_attrs = (self.build_attrs(self.attrs, attrs)
                        if self.option_inherits_attrs else {})
        # Begin modification
        # If the value we were passed is a tuple/list then split it
        # into a value and an attrs dict
        if isinstance(value, (list, tuple)):
            option_attrs.update(value[1])  # add to any existing attrs
            value = value[0]
        # End modification
        if selected:
            option_attrs.update(self.checked_attribute)
        if 'id' in option_attrs:
            option_attrs['id'] = self.id_for_label(option_attrs['id'], index)
        return {
            'name': name,
            'value': value,
            'label': label,
            'selected': selected,
            'index': index,
            'attrs': option_attrs,
            'type': self.input_type,
            'template_name': self.option_template_name,
        }


class ImageJobForm(forms.Form):
    """ Django form that allows users to create image jobs """
    imagetype = forms.ChoiceField(
        label='Image type',
        choices=[],
        help_text="Type: format of image you want to produce.")

    architecture = forms.ChoiceField(
        label='Architecture',
        choices=[],
        help_text="Target architecture of the image you want to build from "
        "your customized kickstart.")

    ksfile = forms.FileField(
        label="Kickstart file", required=False,
        help_text="Kickstart: customized kickstart file, "
        "if the templates don't fit your needs.")

    template = OptionAttrChoiceField(
        label='Template',
        choices=[("None", "None")],
        widget=OptionAttrSelect,
        help_text="Template: Choose a base template ontop of which your "
        "packages will be added. Each template is targeted at a certain "
        "device and architecture so the architecture and kickstart "
        "fields will be ignored.")

    features = forms.TypedMultipleChoiceField(
        label="Features", choices=[],
        help_text="Features: Commonly used extra features",
        empty_value={},
        coerce=expand_feature, required=False,
        widget=forms.widgets.CheckboxSelectMultiple)

    overlay = forms.CharField(
        label="Packages", required=False,
        widget=forms.Textarea(attrs={'rows': '1'}),
        help_text="Packages: comma separated list of packages you want to "
        "include in the image built from the chosen template. A packagename "
        "prefixed with '-' are excluded. Package groups are denoted by "
        "'@' prefix.")

    pinned = forms.BooleanField(
        label="Pin image", required=False,
        initial=False,
        help_text="Pin image so it doesn't expire or get deleted by mistake.")

    tags = forms.CharField(
        label="Tags", required=False,
        widget=forms.Textarea(attrs={'rows': '1'}),
        help_text="Packages: comma separated list of tags to describe the "
        "image built.")

    devicemodel = forms.CharField(
        label="Device model",
        required=False,
        widget=forms.HiddenInput(attrs={'readonly': 'readonly'}))

    devicevariant = forms.CharField(
        label="Device variant",
        required=False,
        widget=forms.HiddenInput(attrs={'readonly': 'readonly'}))

    brand = forms.CharField(
        label="Brand",
        required=False,
        widget=forms.HiddenInput(attrs={'readonly': 'readonly'}))

    def __init__(self, *args, **kwargs):
        super(ImageJobForm, self).__init__(*args, **kwargs)
        choices = []
        suggested_re = re.compile(
            r'^#.*?Suggested(Architecture|ImageType|Features):(.*)$'
        )

src/img_web/templates/app/job_details.html
{% extends 'base.html' %}

{% block pagetitle %}Detailed view{% endblock %}

{% block title %}Detailed view{% endblock %}

{% block content %}

{% include "app/messages.html" %}

{% if errors %}
<div class="errors">
  {% for label, e in errors.items %}
    {{ label }} : {{ e|join:", " }}
  {% endfor %}
</div>
{% endif%}
<div id="details" class="details">
<table>
<tr>
<td>ID : {{ obj.image_id }}</td>
<td>Created : {{ obj.created|date:"SHORT_DATETIME_FORMAT" }}</td>
</tr>
<tr>
<td>Owner : {{obj.user.username}}</td>
<td>Type : {{obj.image_type}}</td>
</tr>
<tr>
<td>Arch : {{obj.arch}}</td>
<td>Status : {{obj.status}}<td>
</tr>
<tr>
<form id="tagform" action="{%url 'img-app-job' obj.image_id %}" method="post" enctype="multipart/form-data">
{% csrf_token %}
<td>
{{ tagform.tags.label_tag }} : {{ tagform.tags }}
</td>
<td>
<input type="submit" value="Save tags" />
</td>
</form>
</tr>
</table>
</div>
<div id="logtext" class="logtext"> 
<iframe id="logframe" src="{{ obj.logfile_url }}" width="100%" height="1000px" scrolling="auto">

</iframe>
<script type="text/javascript">
x=document.getElementById("logframe");
x.onload = function () { x.contentWindow.scrollTo(0, x.contentWindow.document.body.scrollHeight); }
var refTimeoutID = window.setInterval('x=document.getElementById("logframe");x.src=x.src;', 20000);
</script>
</div>
<div>
</div>
<script type="text/javascript">
</script>
{% endblock %}
{% block sidebar_title %}
Actions
{% endblock %} 
{% block sidebar_content %}
<li>
This page will refresh automatically every 20 seconds.
</li>
<li>
<a name="bottom" href="#bottom" onclick="if (refTimeoutID) window.clearInterval(refTimeoutID)">Stop auto-refresh</a>
</li>
<li>
{% include 'app/ops.html' %}
</li>
{% endblock %} 

src/img_web/templates/app/messages.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags == "error" %}
        <div class="errors">{{ message }}</div>
        {% else %} {% if message.tags == "warning" %}
        <div class="warning">{{ message }}</div>
        {% else %}
        <div class="info">{{ message }}</div>
        {% endif %}
        {% endif %}
    {% endfor %}
{% endif %}

src/img_web/templates/app/ops.html
<a href="{% url 'img-app-job' obj.image_id %}"><img src="{{ STATIC_URL }}/images/details.png" width="24" height="24" alt="Log" title="View image details and build log"></img></a>
{% if obj.files_url %}
<a href="{{ obj.files_url }}/"><img src="{{ STATIC_URL }}/images/folder.png" width="24" height="24" alt="Files" title="View image build directory"></img></a>
{% endif %}
{% if obj.image_url %}
<a href="{{ obj.image_url }}"><img src="{{ STATIC_URL }}/images/download.png" width="24" height="24"  alt="Image" title="Download built image"></img></a>
{% endif %}
<a href="{% url 'img-app-job' obj.image_id %}"><img src="{{ STATIC_URL }}/images/tag.png" width="24" height="24"  alt="Retry" title="Change or add this jobs' tags"></img></a>
{% if obj.queue.handle_launch %}
<a href="{% url 'img-app-retry-job' obj.image_id %}"><img src="{{ STATIC_URL }}/images/retry.png" width="24" height="24"  alt="Retry" title="Resubmit image as a new job"></img></a>
{% endif %}
<a href="{% url 'img-app-retest-job' obj.image_id %}"><img src="{{ STATIC_URL }}/images/test.png" width="24" height="24"  alt="Re-test" title="Test or Retest same image"></img></a>
<a href="{% url 'img-app-delete-job' obj.image_id %}"><img src="{{ STATIC_URL }}/images/trash.png" width="24" height="24" alt="Delete" title="Request deletion of this image"></img></a>
{% if obj.pinned %}
<a href="{% url 'img-app-toggle-pin-job' obj.image_id %}"><img src="{{ STATIC_URL }}/images/pin_red.png" width="24" height="24" alt="unpin" title="This image is pinned and will not expire or be deleted, click to unpin it"></img></a>
{% else %}
<a href="{% url 'img-app-toggle-pin-job' obj.image_id %}"><img src="{{ STATIC_URL }}/images/pin_black.png" width="24" height="24" alt="pin" title="Click to pin this image so it doesn't expire or be deleted"></img></a>
{% endif %}

src/img_web/templates/app/queue.html
{% extends 'base.html' %}

{% load app_tags %}

{% block pagetitle %}IMG Queue{% endblock %}

{% block title %}
{% if filtered %}
    {{ user.username }}'s images
{% else%}
    {%if queue_name %}
        {{ queue_name }} image creation queue
    {% else %}
        All image creation queues
    {% endif %}
{% endif %}

{% endblock %}

{% block content %}

{%if queue %}
<meta http-equiv="refresh" content="60">
{% include "app/messages.html" %}
<table id="queue">
    <thead>
        <tr>
            <th>ID {%if not queue_name %}/ queue{% endif %} / User</th>
            <th>Name</th>
            <th>Arch / Type</th>
            <th>Submitted / Length</th>
            <th>Status</th>
            <th>Results / Operations</th>
        </tr>
    </thead>
    <tbody>
        {% for obj in queue.object_list %}
        <tr>
            <td>{{ obj.image_id }}<br/>{%if not queue_name %}/ {{ obj.queue.name }}{% endif %} / {{obj.user.username}}</td>
            <td>{{ obj.name }}</td>

            <td>{{obj.arch}}
                <br/>
            {{obj.image_type}} </td>
            <td>{{ obj.created|date:"m/d/Y G:i" }}
             <br/>
            {{obj.created|timesince:obj.done}}</td>
            <td>
                {{obj.status}}
                <br/>
                {% if obj.status == "DONE, TESTED" %}
                    {% if obj.test_result %}
                    <font color="green">PASS</font>
                    {% else%}
                    <font color="red">FAIL</font>
                    {% endif %}
                {% endif %}
            </td> 
            <td>
                {% include 'app/ops.html' %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
    <tfoot>
        <tr class="pagination">
            <td>
            {% if queue.has_previous %}
                <a href="?page={{ queue.previous_page_number }}">previous</a>
            {% endif %}
            </td>
            <td colspan="4">
                Page {{ queue.number }} of {{ queue.paginator.num_pages }}.
            </td>
            <td>
            {% if queue.has_next %}
                <a href="?page={{ queue.next_page_number }}">next</a>
            {% endif %}
            </td>
        </tr>
    </tfoot>
</table>
{% endif %}
{% endblock %}
{% block sidebar_title %}
Filter
{% endblock %}
{% block sidebar_content %}
<li>
{% if filtered %}
Show <a href="{%url 'img-app-queue' %}">all images</a>
{% else%}
Show <a href="{%url 'img-app-queue-filter' %}">only my images</a>
{% endif %}
</li>
<li>
Show queue: 
{% for q in queues %}
{% if q.name not in request.path %}
<a href="{% url 'img-app-queue-name' queue_name=q.name %}">{{ q.name }} </a>
{% endif %}
{% endfor %}
{% if queue_name %}
<a href="{% url 'img-app-queue' %}">all </a>
{% endif %}
</li>
<li>
This page will auto-refresh every 60 seconds.
</li>
<li>
<a name="bottom" href="#bottom" onclick="if (refTimeoutID) window.clearTimeout(refTimeoutID)">Stop auto-refresh</a>
<script type="text/javascript">
  var refTimeoutID = window.setTimeout('location.reload();', 60000);
</script>
</li>
{% endblock %}

src/img_web/templates/app/search.html
{% extends 'base.html' %}

{% block pagetitle %}Search{% endblock %}

{% block title %}Search{% endblock %}

{% block content %}

{% include "app/messages.html" %}

{% if errors %}
<div class="errors">
  {% for label, e in errors.items %}
    {{ label }} : {{ e|join:", " }}
  {% endfor %}
</div>
{% endif%}
<div>
<table>
<tr>
<form id="searchform" action="{% url 'img-app-search' %}" method="post" enctype="multipart/form-data">
{% csrf_token %}
<td>
{{ searchform.searchterm }}
</td>
<td>
<input type="submit" value="Search tags" />
</td>
</form>
</tr>
</table>
</div>
<hr/>
<div id="search_results" class="search_results">
<p>All tags (click on one to search for all images with that tag):<br/>
{% for x in alltags %}
<a href="{% url 'img-app-search-tag' tag=x %}">{{ x }}</a>
{% endfor %}
</p>
<p>
{% if results %}
<p>Results</p>
{% for x in results %}
<a href="{%url 'img-app-job' msgid=x.image_id %}">{{ x.image_id }}</a>
{% endfor %}
{% endif%}
</p>
</div>
{% endblock %}
{% block sidebar_title %}
Help
{% endblock %} 
{% block sidebar_content %}
<li>
Something
</li>
{% endblock %} 

src/img_web/templates/app/upload.html
{% extends 'base.html' %}

{% block pagetitle %}IMG image uploader{% endblock %}

{% block title %}Image creation request{% endblock %}

{% block content %}
<script type="text/javascript">
    $(function() {
        $('#id_extra_repos_table tbody tr').formset({
            extraClasses: ['row1', 'row2', 'row3']
        });
        $('#id_ksfile').attr("disabled","disabled");
        $('#template').attr("checked","checked");
        $('#ksfile , #template').change(function(e){
            var enid = '' + $(e.target).attr('id');
            var dissel = 'input:radio:not([id=' + enid + '])';
            var disid = $(dissel).attr('id');
            $('#id_'+enid).removeAttr("disabled");
            $('#id_'+disid).attr("disabled","disabled");
            if (disid == 'template') { $('#id_'+disid).val("None") }
            else if(disid == 'ksfile') { $('#id_'+disid).val("") }
        });
        $("#uploadform").submit( function () {
           $('#id_ksfile , #id_template').each(function(){ $(this).removeAttr("disabled")});
           return true; 
        } );
        $("select[name=template]").change(function() {
           var selected = $(this).val();
           var selected_elem = $("option[value$='" + selected + "']");
           $($(selected_elem)[0].attributes).each( function() {
             var x = this;
             if (x.name.match(/^data-/)) {
               var y = x.name.replace("data-", "");
               if (x.value.match(/,/)) {
                 $(x.value.split(",")).each( function() {
                   $("[name=" + y + "][value=" + this + "]").attr("checked", true);
                 });
               } else {
                 $("[name=" + y + "]").val(x.value);
               }
             }
           });
        });

    })
</script>
{% if jobform.is_bound %}
<div class="errors">
    {% if jobform.errors %}
        {% for label, error in jobform.errors.items %}
            {{ error }}
        {% endfor %}
    {% endif %}
    {% if tokensformset.errors %}
        {% for x in tokensformset.errors %}
            {% for label, error in x.items %}
                {{ error }}
            {% endfor %}
        {% endfor %}
    {% endif %}
    {% if reposformset.errors %}
        {% for x in reposformset.errors %}
            {% for label, error in x.items %}
                {{ error }}
            {% endfor %}
        {% endfor %}
    {% endif %}
</div>
{% endif %}
<form id="uploadform" action="{%url 'img-app-submit' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset>
        <legend>Basic options</legend>
    <table width="100%">
        <tr>
            <td>
              <input type="radio" name="choice" id="{{ jobform.template.name }}"/>
            {{ jobform.template.label_tag }}
            </td>
            <td>
            {{ jobform.template }}
            </td>
        </tr>
        <tr border="15px">
        <td>-OR-</td>
        <td></td>
        </tr>
        <tr>
            <td>
              <input type="radio" name="choice" id="{{ jobform.ksfile.name }}"/>
            {{ jobform.ksfile.label_tag }}
            </td>
            <td>
            {{ jobform.ksfile }}
            </td>
        </tr>
        <tr>
            <td>
            {{ jobform.imagetype.label_tag }}
            </td>
            <td>
            {{ jobform.imagetype }}
            </td>
        </tr>
        <tr>
            <td>
            {{ jobform.architecture.label_tag }}
            </td>
            <td>
            {{ jobform.architecture }}
            </td>
        </tr>
        </table>
        {{ jobform.devicemodel }} {{ jobform.devicevariant }} {{ jobform.brand }}
    </fieldset>
</table>
<fieldset> 
    <legend>Kickstart token mappings</legend>
    <table id="id_kickstart_token_mappings_table" border="0" cellpadding="0" cellspacing="5">
         <thead>
             <tr>
                 <th scope="col">Token</th>
                 <th scope="col">Value</th>
                 <th scope="col">Description</th>
             </tr>
         </thead>
         <tbody>
             {% for tokensform in tokensformset.forms %}
             {% for f in tokensform %}
             <tr>
                 <td>{{ f.label_tag }}</td>
                 <td>{{ f }}</td>
                 <td>{{ f.help_text }}</td>
             </tr>
             {% endfor %}
             {% endfor %}
         </tbody>
     </table>
    {{ tokensformset.management_form }}
</fieldset>
<fieldset>
    <legend>Optional Features</legend>
    <div id="features">
        {{ jobform.features }}
    </div>
</fieldset>
    <p><input type="submit" value="Submit" /></p>
<fieldset>
    <legend>Metadata options</legend>
    <table width="100%">
        <tr>
            <td>
            {{ jobform.pinned.label_tag }}
            </td>
            <td>
            {{ jobform.pinned }}
            </td>
        </tr>
        <tr>
            <td>
            {{ jobform.tags.label_tag }}
            </td>
            <td>
            {{ jobform.tags }}
            </td>
        </tr>
    </table>
</fieldset>
<fieldset>
    <legend>Extra repositories and packages</legend>
    <table id="id_extra_repos_table" border="0" cellpadding="0" cellspacing="5">
         <thead>
             <tr>
                 <th scope="col">OBS</th>
                 <th scope="col">Project</th>
                 <th scope="col">Repository</th>
             </tr>
         </thead>
         <tbody>
             {% for f in reposformset.forms %}
             <tr id="{{ f.prefix }}-row">
                 <td>{{ f.obs }}</td>
                 <td>{{ f.project }}</td>
                 <td>{{ f.repo }}</td>
             </tr>
             {% endfor %}
         </tbody>
     </table>
    {{ reposformset.management_form }}
    <table>
    <tr>
        <td>
            {{ jobform.overlay.label_tag }}
        </td>
        <td>
            {{ jobform.overlay }}
        </td>
    </tr>
    </table>
</fieldset>

<fieldset>
    <legend>Post processing</legend>
    <table>
         <tbody>
             {% for ppform in ppformset %}
             <tr>
             {% for f in ppform %}

                 <td>
                     {{ f }}
                     {% if forloop.first %}{{ f.label_tag }}{% endif %}
                 </td>
                 {% if forloop.last %}
                   <td>
                     {{ f.help_text }}
                   </td>
                 {% endif %}

             {% endfor %}
             </tr>
             {% endfor %}
         </tbody>
     </table>
    {{ ppformset.management_form }}
</fieldset>

<p><input type="submit" value="Submit" /></p>
</form>

{% endblock %}
{% block sidebar_title %}
Help
{% endblock %}
{% block sidebar_content %}
    {% for field in jobform %}
    <li>{{ field.help_text }}</li>
    {% endfor %}
    {% for f in reposformset.forms %}
      {% for field in f %}
        <li>{{ field.help_text }}</li>
      {% endfor %}
    {% endfor %}
{% endblock %}